#!/bin/sh
# Managing number of stray sessions caused by running tmux on terminal startup
# Resumes a defaultly named session if it is unattached

# pass the terminal with its exection
term_and_run=$1

# Number only sessions that are not attached
generic_sessions=$(tmux list-sessions \
  | grep --invert-match '(attached)$' \
  | grep '^[[:digit:]]*:'
)

if [ -z "$generic_sessions" ]; then
  $term_and_run tmux
else
  first_generic_session=$(echo "$generic_sessions" | head -n 1 | sed 's/\:.*//')
  $term_and_run tmux attach-session -t "$first_generic_session"
fi
