#!/bin/sh
# Managing number of stray sessions caused by running tmux on terminal startup
# Resumes a defaultly named session if it is unattached

# pass the terminal with its exection
TERM_AND_RUN=$1

# Number only sessions that are not attached
GENERIC_SESSIONS=$(tmux list-sessions \
  | grep --invert-match '(attached)$' \
  | grep '^[[:digit:]]*:'
)

if [ -z "$GENERIC_SESSIONS" ]; then
  $TERM_AND_RUN tmux
else
  FIRST_GENERIC_SESSION=$(echo "$GENERIC_SESSIONS" | head -n 1 | sed 's/\:.*//')
  $TERM_AND_RUN tmux attach-session -t $FIRST_GENERIC_SESSION
fi
