#!/usr/bin/env sh
  # $0 <path>
# Deal with processing the arguments of ls ?

# Default to '.' if argument is provided
target="$(namedpath "${1:-.}" || exit "$?")"

if   [ -d "${target}" ]; then
  cd "$target" || exit "$?"
elif [ -f "${target}" ]; then
  dir="$(dirname "${target}"; echo 'x')"; dir="${dir%??}"
  cd "${dir}" || exit "$?"
else
  exit 1
fi

[ "$#" -gt 0 ] && shift 1
pwd -P
ls --group-directories-first --color=auto -A . "$@"
