#!/usr/bin/env sh
  # $0 <path>
# Deal with processing the arguments of ls ?
# Also follows folder aliases from 'namedpath'

# Default to '.' if argument is provided
input="${1:-.}"

target="$(namedpath "${input}"; printf 'x')"; target="${target%?}"

if   [ -d "${target}" ]; then
  cd "${target}" || exit "$?"
elif [ -f "${target}" ]; then
  dir="$(dirname "${target}"; printf 'x')"; dir="${dir%??}"
  cd "${dir}" || exit "$?"
else
  exit 1
fi

[ "$#" -gt 0 ] && shift 1
pwd -L
ls --group-directories-first --color=auto -A . "$@"
