#!/bin/sh
# https://stackoverflow.com/questions/6429515
stty -ixon -ixoff # Archaic with modern CPU/modem speeds. Reclaims C-q and C-s

alias    ab='abook --datafile "${HOME}/.config/abook/addressbook"'
alias     b='vifm .'
alias  diff='diff --color=auto'
alias    eb='browser.sh edit bookmarks'
alias    ee='es'
alias    es='browser.sh edit search'
alias    ga='git add'
alias    gc='git commit --message'
alias    gn='git clone --recursive'
alias   glg="git log --graph --abbrev-commit --decorate --oneline --all"
alias    gp='git push --recurse-submodules=on-demand'
alias    gs='git status'
#alias  gcb='sh -c "
#  git checkout -b \"$1\"
#  git submodule foreach '\''git checkout -b \"$1\"'\''
#" _'
#alias    gu='git submodule update --remote --merge'
alias  grep='grep --color=auto'
alias     l='ls -h --group-directories-first'
alias    ls='ls --color=auto'
alias    la='l -A'
alias   lal='l -Al'
alias    ll='l -l'
alias   mkf='sh -c "for x in \"\$@\"; do
  touch -- \"\$x\"
  chmod 644 -- \"\$x\"
done" _'
alias   mks='sh -c "for x in \"\$@\"; do
  touch -- \"\$x\"
  chmod 755 -- \"\$x\"
done" _'
alias    nm='sudo nmtui'
alias    pm='package-manager.sh'
alias    rb='trash'
alias    rx='xrdb ~/.Xresources'
#alias  rrc=''  # In individual rc files, reminder to not re-alias this
alias   scb='browser.sh copy bookmarks'
alias   sgl='browser.sh gui link'
alias   sgb='browser.sh gui bookmarks'
alias   sge='browser.sh gui search'
alias   sml='browser.sh menu link'
alias   smb='browser.sh menu bookmarks'
alias   sme='browser.sh menu search'
alias   stl='browser.sh terminal link'
alias   stb='browser.sh terminal bookmarks'
alias   ste='browser.sh terminal search'
alias xcaps='xdotool key Caps_Lock'
alias     t='tmux.sh'
alias     w='weather.sh'
alias     v='nvim'

# This works though, just for bash, need to test on other shells
#alias     c='c() {
#  if [ -z "$1" ]; then "${SCRIPTS}/namedpath.sh" --list-aliases >&2
#    printf "."
#}; \c'

# Well this does not work, meep
#alias c='cd "$(sh -c '\''
#  if [ -z "$1" ]; then
#    "${SCRIPTS}/namedpath.sh" --list-aliases >&2
#    printf "."
#    ls -Ah --group-directories-first --color=auto
#  else
#    #path="$("${SCRIPTS}/namedpath.sh" "$1"; printf x)"; path="${path%?}"
#    #cd "${path}" && ls -Ah --group-directories-first --color=auto
#
#    # Command substitution $(...) strips trailing newlines, unsure how to solve
#    path="$("${SCRIPTS}/namedpath.sh" "$1" >&2)"
#    [ -d ${path} ] && ls -Ah --group-directories-first --color=auto
#  fi
#'\'' _)"'


alias debug-path='printf %s\\n "${PATH}" | tr ":" "\n" | sort'

# -i list all Internet and x.25 network files
# -n prevents conversion of network numbers to host names (DNS translation)
# -l prevents conversion of user id numbers to login names
# -P prevents conversion of port numbers to port names
uname -o | grep -q 'GNU/Linux' && alias list-open-ports='lsof -i -nlP \
  | awk "{print \$9, \$8, \$1}" | sed "s/.*://" | sort -u'
uname -o | grep -q 'Android' && alias list-open-ports='lsof -i -nlP'
alias list-imes='<~/.config/fcitx/profile \
  sed -n "/^EnabledIMList=/{ s/^.*=//p; }" \
  | awk -v RS="," -v FS=":" "(\$2 ~ /True/){ print \$1; }"'
alias pipugradeall='python -m pip install --upgrade $(
  python -m pip list --outdated | awk "(NR > 2){ print \$0;}")'
#alias npmexec='printf "%s/%s" "$(npm bin)"'
alias rimeinstall='rime_frontend=fcitx-rime \
  bash $HOME/ime/rime-plum/rime-install'
