#!/bin/sh
# https://stackoverflow.com/questions/6429515
stty -ixon -ixoff # Archaic with modern CPU/modem speeds. Reclaims C-q and C-s

alias     l='ls -h --group-directories-first --color=auto'
alias  grep='grep --color=auto'
alias  diff='diff --color=auto'

alias    rx='xrdb ~/.Xresources'
alias xcaps='xdotool key Caps_Lock'

#alias npmexec='printf "%s/%s" "$(npm bin)"'
alias rimeinstall='rime_frontend=fcitx-rime bash $HOME/ime/rime-plum/rime-install'
