#!/usr/bin/env sh

# prints in the format of escaped quotes, itself quoted, with a trailing space
# eg. <'spaces'\'and quotes.txt' >  which will matches <spaces'and quotes.txt>
out() { printf "'%s' " "$@"; }

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
out "a" "${XDG_CONFIG_HOME}/nvim/after"
out "b" "${HOME}/blog"
out "c" "${XDG_CONFIG_HOME}"
out "d" "$(c.sh downloads)"
out "e" "${DOTENVIRONMENT}"
out "f" "${HOME}/Documents"
out "h" "${HOME}/dotfiles"
out "i" "${HOME}/interim"
out "m" "${HOME}/Music"
out "n" "${DOTENVIRONMENT}/notes"
out "o" "${HOME}/dotfiles/share"
out "p" "${HOME}/projects"
out "s" "${SCRIPTS}"
out "t" "${TMPDIR}"
