#!/usr/bin/env sh

# prints in the format of escaped quotes, itself quoted, with a trailing space
# eg. <'spaces'\'and quotes.txt' >  which will matches <spaces'and quotes.txt>
out() { printf "'%s' " "$@"; }

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
out "a"  "${XDG_CONFIG_HOME}/nvim/after"
out "b"  "${DOTENVIRONMENT}/notes/blog"
out "cl"  "${XDG_DATA_HOME}/.."
out "dc" "${HOME}/dotfiles/.config"
out "c"  "${XDG_CONFIG_HOME}"
out "d"  "$( c.sh downloads )"
out "e"  "${DOTENVIRONMENT}"
out "ec"  "${DOTENVIRONMENT}/.config"
out "el"  "${DOTENVIRONMENT}/Library"
out "f"  "$( c.sh documents )"
out "h"  "${HOME}/dotfiles"
out "i"  "${HOME}/interim"
out "l"  "${HOME}/Library"
out "m"  "${HOME}/Music"
out "n"  "${DOTENVIRONMENT}/notes"
out "o"  "${HOME}/dotfiles/share"
out "p"  "${HOME}/Pictures"
out "s"  "${SCRIPTS}"
out "sn" "${XDG_CONFIG_HOME}/snippets"
out "t"  "${TMPDIR}"
out "w"  "${HOME}/projects"
out "q"  "$( c.sh downloads )/queue"
out "z"  "${DOTENVIRONMENT}/zettelkasten"
