theme = "catppuccin_latte"

[editor]
auto-format  = false
auto-pairs   = false
bufferline   = "multiple"
cursor-shape = { insert = "bar" } # Visual indication we are in insert mode
color-modes  = true
line-number  = "relative"
rulers       = [81]
soft-wrap    = { enable = true } # I want all text displayed
true-color   = true

lsp        = { display-messages = true }
# I want the branch name displayed
statusline = { left = ["mode", "file-name", "version-control", "spinner"] } 


[keys.normal]
esc   = ["collapse_selection", "keep_primary_selection"]
"$"   = "extend_to_line_end"    # Vim muscle memory
0     = "extend_to_line_start"  # Vim muscle memory
","   = "extend_line_below"     # Vim muscle memory for 'x'
x     = "delete_selection"      # Vim muscle memory for 'x'
D     = "kill_to_line_end"
space = { w = ":write", q = ":quit" }

[keys.select]
"x"   = "delete_selection"      # Vim muscle memory for 'x'
","   = "extend_line_below"     # Vim muscle memory for 'x'

[keys.insert.tab]
v     = "paste_clipboard_before"

# Snippets
#n     = ["search", "<>"]
tab   = ":insert-output tmux-window-output-to-buffer.sh snippets.sh \"$HX_EXT\""
[keys.insert.tab.s]
a     =  ":insert-output tmux-window-output-to-buffer.sh snippets.sh"
s     =  ":insert-output tmux-window-output-to-buffer.sh snippets.sh \"symbols\""

[keys.normal."\\"]
q     = ":sh [ -n \"${TMUX}\" ] && tmux new-window -d build.sh background --temp \"$HX_PATH\""
w     = [":write", ":sh tmux-alt-pane.sh send-keys \"build.sh build --temp \" \"$HX_PATH\" Enter"]
e     = [":write", ":sh tmux-editor-run.sh \"$HX_EXT\" \"$HX_PATH\""]
r     = ":sh tmux-alt-pane.sh send-keys \"build.sh run --temp \" \"$HX_PATH\" Enter"
t     = ":sh tmux-alt-pane.sh kill-pane"
l     = ":sh tmux-alt-pane.sh send-keys \"build.sh lint \" \"$HX_PATH\" ENTER"
c     = "yank_main_selection_to_clipboard"
v     = "paste_clipboard_before"

