# Control which grammars are fetched and built
use-grammars = { only = [
  "awk", "bash", "bibtex", "c", "c-sharp", "css", "diff", "java", "javascript", 
  "jsdoc", "json", "jsx", "julia", "git-rebase", "go", "gotmpl", "hcl", "html",
  "latex", "lua", "make", "markdown", "markdown.inline", "mermaid", "msbuild",
  "nim", "nix", "org", "passwd", "perl", "php", "python", "r", "rmarkdown",
  "ruby", "rust", "scala", "scheme", "scss", "sql", "tfvars", "toml",
  "typescript", "tsx", "vim", "xml", "yaml", "zig"
] }

[[language]]
name            = "nix"
scope           = "source.nix"
language-server = { command = "rnix-lsp" }

[[language]]
name            = "rust"
scope           = "source.rs"
language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"] }
#debugger        = { name = "probe", transport = "stdio", command = "lldb", args = [] }

[[language]]
name            = "hcl"
scope           = "source.hcl"
language-server = { command = "terraform-lsp" }

[[language]]
name            = "tfvars"
scope           = "source.tfvars"
language-server = { command = "terraform-lsp" }

[[language]]
name            = "tfvars"
scope           = "source.tfvars"

[[language]]
name            = "vim"
injection-regex = "vim"
scope           = "source.vim"
file-types      = ["vim", "vimrc"]
roots           = []
comment-token   = "#"
indent          = { tab-width = 2, unit = "  " }
[[grammar]]
name            = "vim"
source          = { git = "https://github.com/vigoux/tree-sitter-viml", rev = "e39a7bbcfdcfc7900629962b785c7e14503ae590"}
#source          = { git = "https://github.com/nvim-treesitter/nvim-treesitter", rev = "21f2fb188e4e5bb81fd0ff467c5e96dad858becb" }



[[language]]
name            = "markdown"
scope           = "source.md"
language-server = { command = "marksman" }

[[language]]
name            = "latex"
scope           = "source.tex"
language-server = { command = "texlab" }



# See helix wiki for deno lsp
[[language]]
name            = "javascript"
shebangs        = ["deno", "node"]
roots           = ["deno.json", "package.json", "tsconfig.json"]
config          = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascript" }

[[language]]
name            = "jsx"
shebangs        = ["deno", "node"]
roots           = ["deno.json", "package.json", "tsconfig.json"]
config          = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascriptreact" }

[[language]]
name            = "typescript"
shebangs        = ["deno", "node"]
roots           = ["deno.json", "package.json", "tsconfig.json"]
config          = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }

[[language]]
name            = "tsx"
shebangs        = ["deno", "node"]
roots           = ["deno.json", "package.json", "tsconfig.json"]
config          = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescriptreact" }
